// Imagenes
export const OBTENER_IMAGEN_HOTEL: string = "OBTENER_IMAGEN_HOTEL";
export const OBTENER_IMAGEN_HOTEL_EXITO: string = "OBTENER_IMAGEN_HOTEL_EXITO";
export const OBTENER_IMAGEN_HOTEL_ERROR: string = "OBTENER_IMAGEN_HOTEL_ERROR";

// Paginas
export const OBTENER_PAGINA: string = "OBTENER_PAGINA";
export const OBTENER_PAGINA_EXITO: string = "OBTENER_PAGINA_EXITO";
export const OBTENER_PAGINA_ERROR: string = "OBTENER_PAGINA_ERROR";

// Habitaciones
export const OBTENER_HABITACIONES: string = "OBTENER_HABITACIONES";
export const OBTENER_HABITACIONES_EXITO: string = "OBTENER_HABITACIONES_EXITO";
export const OBTENER_HABITACIONES_ERROR: string = "OBTENER_HABITACIONES_ERROR";

// SEO
export const OBTENER_SEO: String = "OBTENER_SEO";
export const OBTENER_SEO_EXITO: String = "OBTENER_SEO_EXITO";
export const OBTENER_SEO_ERROR: String = "OBTENER_SEO_ERROR";