// imagenes
export const OBTENER_LOGO: string = 'OBTENER_LOGO';
export const OBTENER_LOGO_EXITO: string = 'OBTENER_LOGO_EXITO';
export const OBTENER_LOGO_ERROR: string = 'OBTENER_LOGO_ERROR';

export const OBTENER_BANNER: string = 'OBTENER_BANNER';
export const OBTENER_BANNER_EXITO: string = 'OBTENER_BANNER_EXITO';
export const OBTENER_BANNER_ERROR: string = 'OBTENER_BANNER_ERROR';

export const OBTENER_ICONOS: string = 'OBTENER_ICONOS';
export const OBTENER_ICONOS_EXITO: string = 'OBTENER_ICONOS_EXITO';
export const OBTENER_ICONOS_ERROR: string = 'OBTENER_ICONOS_ERROR';

// Paginas
export const OBTENER_PAGINA_INICIO: string = 'OBTENER_PAGINA_INICIO';
export const OBTENER_PAGINA_INICIO_EXITO: string = 'OBTENER_PAGINA_INICIO_EXITO';
export const OBTENER_PAGINA_INICIO_ERROR: string = 'OBTENER_PAGINA_INICIO_ERROR';

// Propiedades
export const OBTENER_PROPIEDADES: string = 'OBTENER_PROPIEDADES';
export const OBTENER_PROPIEDADES_EXITO: string = 'OBTENER_PROPIEDADES_EXITO';
export const OBTENER_PROPIEDADES_ERROR: string = 'OBTENER_PROPIEDADES_ERROR';