// Usuarios
export const CREAR_CUENTA: string = 'CREAR_CUENTA';
export const CREAR_CUENTA_EXITO: string = 'CREAR_CUENTA_EXITO';
export const CREAR_CUENTA_ERROR: string = 'CREAR_CUENTA_ERROR';

export const AUTENTICAR_USUARIO: string = 'AUTENTICAR_USUARIO';
export const AUTENTICAR_USUARIO_EXITO: string = 'AUTENTICAR_USUARIO_EXITO';
export const AUTENTICAR_USUARIO_ERROR: string = 'AUTENTICAR_USUARIO_ERROR';

export const USUARIO_AUTENTICADO: string = 'USUARIO_AUTENTICADO';
export const USUARIO_AUTENTICADO_EXITO: string = 'USUARIO_AUTENTICADO_EXITO';
export const USUARIO_AUTENTICADO_ERROR: string = 'USUARIO_AUTENTICADO_ERROR';

export const CERRAR_SESION: string = 'CERRAR_SESION';

// Archivos
export const SUBIR_ARCHIVO: string = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO: string = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR: string = 'SUBIR_ARCHIVO_ERROR';

// Enlaces
export const CREAR_ENLACE: string = 'CREAR_ENLACE';
export const CREAR_ENLACE_EXITO: string = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR: string = 'CREAR_ENLACE_ERROR';

export const OBTENER_ENLACE: string = 'OBTENER_ENLACE';
export const OBTENER_ENLACE_EXITO: string = 'OBTENER_ENLACE_EXITO';
export const OBTENER_ENLACE_ERROR: string = 'OBTENER_ENLACE_ERROR';

export const OBTENER_ENLACES: string = 'OBTENER_ENLACES';
export const OBTENER_ENLACES_EXITO: string = 'OBTENER_ENLACES_EXITO';
export const OBTENER_ENLACES_ERROR: string = 'OBTENER_ENLACES_ERROR';

export const LIMPIAR_ENLACE: string = 'LIMPIAR_ENLACE';

export const AGREGAR_PASSWORD: string = 'AGREGAR_PASSWORD';
export const AGREGAR_DESCARGAS: string = 'AGREGAR_DESCARGAS';

export const VERIFICAR_PASSWORD: string = 'VERIFICAR_PASSWORD';
export const VERIFICAR_PASSWORD_EXITO: string = 'VERIFICAR_PASSWORD_EXITO';
export const VERIFICAR_PASSWORD_ERROR: string = 'VERIFICAR_PASSWORD_ERROR';

// Alertas
export const LIMPIAR_ALERTA: string = 'LIMPIAR_ALERTA';
export const MOSTRAR_ALERTA: string = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA: string = 'OCULTAR_ALERTA';